encyclopedia/urls.py
from django.urls import path
from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="title"),
    path("search/", views.search, name="search"),
    path("new/", views.newEntry, name="new"),
    path("edit/<str:title>", views.editEntry, name="edit"),
    path("random", views.randomEntry, name="random"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django import forms
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
import random
from . import util

class NewEntryForm(forms.Form):
  title = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'Add a new title'}))
  content = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control md-textarea mb-3', 'rows': 3}))

def index(request):
	return render(request, "encyclopedia/index.html", {
			"entries": util.list_entries()
	})
    
def entry(request, title):
	entry = util.get_entry(title)
			
	if entry == None:
		return render(request, "encyclopedia/not-found.html", {
				"title": title,
				"entry": entry
		})
			
	else:
		return render(request, "encyclopedia/title-entry.html", {
				"title": title,
				"entry": entry
		})
        
def search(request):
	if request.method == "POST":
      
		new_search = request.POST['q'].strip()
		entry = util.get_entry(new_search)
		entries = util.list_entries()
		search_arr = []
		error_msg = f"{new_search}, there are no matches."
  
		if entry:
			return render(request, "encyclopedia/title-entry.html", {
				"title": new_search,
				"entry": entry
			})
   
		else:
			for search in entries:
				if new_search in search:
					search_arr.append(search)
     
			if not search_arr:
				print(search_arr)
				return render(request, "encyclopedia/match-search.html", {
					"error_msg": error_msg
				})
			
		return render(request, "encyclopedia/match-search.html", {
			"matches": search_arr,
		})
  
def newEntry(request):
  
	titles = util.list_entries()
 
	if request.method == 'POST':
		form = NewEntryForm(request.POST)
  
		if form.is_valid():
			new_title = form.cleaned_data['title']
			new_content = form.cleaned_data['content']
			error_msg = f"The {new_title} title, already exist."
   
			if new_title in titles:
				return render(request, "encyclopedia/new.html", {
      		"form": NewEntryForm(),
					"error_msg": error_msg
				})
     
			else:
				util.save_entry(new_title, new_content)
				return render(request, "encyclopedia/title-entry.html", {
					"title": new_title,
					"entry": new_content
				})
 
	return render(request, "encyclopedia/new.html", {
			"form": NewEntryForm()
	})
 

def editEntry(request, title):
	entry = util.get_entry(title)
 
	if entry is not None:
	
		if request.method == 'POST':
			form = NewEntryForm(request.POST)
			error_msg = f"The {title} must be has a content."
   
			if form.is_valid():
				edited_content = form.cleaned_data['content']

				util.save_entry(title, edited_content)
				return render(request, 'encyclopedia/title-entry.html', {
						"title": title,
						"entry": edited_content
					})
			else:
				return render(request, 'encyclopedia/editEntry.html', {
					"title": title,
					"entry": entry,
					"error_msg": error_msg
				})

		else:
			return render(request, 'encyclopedia/editEntry.html', {
				"title": title,
				"entry": entry
			})
   
	return render(request, "encyclopedia/not-found.html", {
	"title": title,
	})
 
def randomEntry(request):
  
	all_titles = util.list_entries()
	random_title = random.choice(all_titles)
	entry = util.get_entry(random_title)

	return render(request, "encyclopedia/title-entry.html", {
		"title": random_title,
		"entry": entry
	})

wiki/views.py
# from django.shortcuts import render

# from encyclopedia import util

# def entry(request, title):
#   return render(request, "titles/title.html", {
#     title: util.list_entries()
#   })

encyclopedia/templates/encyclopedia/editEntry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  Edit-entry
{% endblock %}

{% block body %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4">
      <div class="alert alert-primary" role="alert">
        <h1 class="text-primary found-title">{{ title }}</h1>
      </div>
      <form action="{% url 'wiki:edit' title %}" method="post">
        {% csrf_token %}
        <input type="text" name="title" value="{{ title }}" hidden>
        <label class="mb-0" for="editEntry">Edit {{ title }} content</label>
        <textarea class="form-control md-textarea mb-3" id="content" name="content" rows="5" vale="{{entry}}">{{ entry }}</textarea>
        <button type="submit" class="btn btn-primary d-block mx-auto">Edit entry</button>
      </form>

      {% if error_msg %}
          <h4 class="text-danger mt-5">{{ error_msg }}</h4>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:title' entry %}">{{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
	<head>
		<title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		<link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
	</head>
	<body>
		<div class="container-fluid">
			<div class="row">
				<div class="sidebar col-lg-2 col-md-3">
					<h2>Wiki</h2>
					<form action="{% url 'wiki:search' %}" method="post">
						{% csrf_token %}
						<input class="search" type="text" name="q" placeholder="Search Encyclopedia">
						<input type="submit" value="search" hidden>
					</form>
					<div>
						<a href="{% url 'wiki:index' %}">Home</a>
					</div>
					<div>
						<a href="{% url 'wiki:new' %}">
							Create New Page
						</a>
					</div>
					<div>
						<a href="{% url 'wiki:random' %}">
							Random Page
						</a>
					</div>
					{% block nav %}
					{% endblock %}
				</div>
				<div class="main col-lg-10 col-md-9">
					{% block body %}
					{% endblock %}
				</div>
			</div>
		</div>

	</body>
</html>

encyclopedia/templates/encyclopedia/match-search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Match - Wiki
{% endblock %}

{% block body %}

 {% if error_msg %}
  <h4 class="text-danger">{{ error_msg }}</h4>
  {% endif %}  

  {% if matches %}
    <h4>Maybe you meant:</h4>
    <ul>
      {% for match in matches %}
      <li><a href="{% url 'wiki:title' match %}">{{ match }}</li></a>
      {% endfor %}
    </ul>
  {% endif %}

{% endblock %}

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New-entry
{% endblock %}

{% block body %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4">
      
      <form action="{% url 'wiki:new' %}" method="post">
        {% csrf_token %}
        <h1 class="mb-4">New Entry</h1>
        <label for="{{ form.title.id_for_lablel }}" class="form-label mb-0">Add a new title</label>
        {{ form.title }}
        <label for="{{ form.content_id_for_label }}" class="form-label mb-0">Add content</label>
        {{ form.content }}
        <button type="submit" class="btn btn-primary d-block mx-auto w-50">Save entry</button>
      </form>

      {% if error_msg %}
          <h4 class="text-danger mt-5">{{ error_msg }}</h4>
      {% endif %}
    </div>
  </div>
</div>


{% endblock %}

encyclopedia/templates/encyclopedia/not-found.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Wiki - {{ title }}
{% endblock %}

{% block body %}

  <div class="container-fluid">
    <div class="alert alert-danger" role="alert">
      <h1 class="text-danger not-found-title">{{ title }}</h1>
      <p class="mt-4">The "{{ title }}" entry doesn`t exist.</p>
    </div>
  </div>

{% endblock %}

encyclopedia/templates/encyclopedia/title-entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Wiki - {{ title }}
{% endblock %}

{% block body %}
  <div class="container-fluid">
    <div class="alert alert-primary" role="alert">
      <h1 class="text-primary found-title">{{ title }}</h1>
      <p class="mt-4">{{ entry }}</p>
    </div>
    <a href="{% url 'wiki:edit' title %}" type="button" class="btn btn-primary">Edit</a>
  </div>
{% endblock %}

wiki/templates/titles/title.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>hello {title}</h1>
</body>
</html>